### PR TITLE
Set -Ofair on worker_default

### PR DESCRIPTION
**Pull request by theresnotime**
It's possible we may _also_ want to set this on `worker_long` / `worker_user`
- See https://progressstory.com/tech/python/production-ready-celery-configuration/#ac32

Bug: [T344936](https://phabricator.wikimedia.org/T344936)

### CODE REVIEW

**Comment by ragesoss** [comment]
This seems safe.

What do the `long` workers do? I haven't figure out how a job ends up in that queue.

**Review by ragesoss — APPROVED** [review]

**Comment by MusikAnimal** [comment]
> What do the long workers do? I haven't figure out how a job ends up in that queue.

I believe it's after something hits the soft time limit in the default queue, i.e. https://github.com/wikimedia/wikiwho_api/blob/c422cb7ff558d37289940af10fd225337968baed/api/tasks.py#L52

**Comment by ragesoss** [comment]
> > What do the long workers do? I haven't figure out how a job ends up in that queue.
> 
> I believe it's after something hits the soft time limit in the default queue, i.e.
> 
> https://github.com/wikimedia/wikiwho_api/blob/c422cb7ff558d37289940af10fd225337968baed/api/tasks.py#L52

What makes that go to the 'long' queue? It this some framework magic that uses expects a "long" queue and automatically puts delayed jobs into it?

**Comment by MusikAnimal** [comment]
My reading is if the `SoftTimeLimitExceeded` exception is thrown when processing the default queue, it gets sent to the long queue

**Pull request merged**
